#%RAML 1.0 DataType 
type: object
properties:
  harvesterID?:  string
  dateOfHarvest?: string
  quotaId?:  string
  scanLatitide?: number
  scanLongitude?:  number
  numFemales?: number
  numWesternGreyKangaroos?:  number
  numPouchYoungDestroyed?: number
  numYoungAtFootDestroyed?:  number
  numTaggedCarcassesLeftOnProperty?: number
  numTaggedCarcassesStoredForProcessor?: number
  comments?: string
  tags?: 
    type: array
    items: !include tags-array.raml
  