#%RAML 1.0 DataType
description: A holding of a customer
type: object
properties:
  id:
    description: Primary identifier of the linked holding
    type: string
    example: a000l00000BaynyAAB
  type:
    description: Type of the holding
    type: string
    example: AGENCY_HOLDING
  subtype:
    description: Sub-type of the holding
    type: string
    example: LICENCE
  name?:
    description: Human-readable name for the holder
    type: string
    example: James Do
  expiry?:
    description: Date and time the asset/holding expires
    type: string
    example: 2020-11-20T10:00:00.000+1100
  tags?:
    type: array
    description: The repeatable name-value pairs with further holding details
    items: !include name-value.raml
  state?: 
    type: string
    description: The state of the holding
  link?:
    description: Link to a holding detail
    type: string