#%RAML 1.0 SecurityScheme
type: Basic Authentication
description: Clientid, Secret Authentication for Api
describedBy:
  headers:
    client_id:
      type: string
    client_secret:
      type: string     
    
    