#%RAML 1.0
title: adapter-djpr-v1
version: v1
baseUri: https://cxisoftware.com.au.gov.au/adapter/v1/djpr-v1
protocols:
  - HTTPS
mediaType: application/json

traits:
  ClientIdEnforceable: !include common/traits/client-id-enforceable.raml
  Countable: !include common/traits/countable.raml
  Pageable: !include common/traits/pageable.raml
  Sortable: !include common/traits/sortable.raml
  Errorable: !include common/traits/errorable.raml
  Trackable: !include common/traits/trackable.raml
  Cacheable: !include common/traits/cacheable.raml
  TimeCacheable: !include common/traits/time-cacheable.raml
  ContentCacheable: !include common/traits/content-cacheable.raml
  
types:
  Holding: !include data-types/holding.raml

securitySchemes:
  OidcJwt: !include security-schemes/oidc-jwt.raml


/holdings:
  /{id}:
    uriParameters:
      id:
        description: The linking key for a holding
        example: "a000l00000BaynyAAB"
    get:
      description:  Get the details of a holding via linking key
      is: [Errorable, Trackable, ClientIdEnforceable]
      responses:
        200:
          body:
            type: Holding
            example: !include examples/get-holding-by-id-response.json

/jobs:
  /create:
    securedBy: [OidcJwt]
    post:
      description:  Get the details of a holding via linking key
      is: [Errorable, Trackable]
      body:
        application/json:
          example: !include examples/create-job-request.json
          type: !include data-types/create-job-request.raml
      responses:
        200:
          body:
              application/json: