#%RAML 1.0 DataType
description: data type for order endpoint request 
type: object
properties:
  orderId:  number
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="api-request">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="xs:string" name="orderId"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>