#%RAML 1.0 SecurityScheme
description: OAuth 2.0 OpenID Connect authentication using JSON Web Tokens
type: OAuth 2.0

describedBy:
  headers:
    Authorization:
      description: The OAuth 2.0 bearer access_token as a compacted, signed JSON Web Token
      type: string
      required: true
      example: Bearer XXXXXXXXXXXXXX
    X-Authentication:
      description: The OAuth 2.0 bearer id_token as a compacted, signed JSON Web Token
      type: string
      required: true
      example: Bearer XXXXXXXXXXXXXX
  responses:
    401:
      description: Malformed or expired token. Re-authenticate to resolve the issue.
    403:
      description: User does not have access to the resource. Re-authentication _will not_ resolve this.
settings:
  authorizationUri: https://cxisoftware.com.au.gov.au/openam/oauth2/authorize
  accessTokenUri: https://cxisoftware.com.au.gov.au/openam/oauth2/token
  authorizationGrants: [ authorization_code, implicit ]