#%RAML 1.0
title: proc-ecomm-api
description: Process layer API for e-ecommerce
version:  v1
protocols: [HTTPS]

traits:
  Errorable:  !include common/traits/errorable.raml

securitySchemes:
  ClientIdAuth: !include common/security/client-id-auth.raml

securedBy: [ClientIdAuth]

/shipments:
  post:
    description: Generic Endpoint for Shipments
    is: [Errorable]
    body:
      application/json:
        type: !include data-types/request/shipments.raml
        example: !include examples/request/shipments.json
    responses:
      200:
        body:
          application/json:


